### ISSUE TITLE
Properly Standardize/Normalize dataframe

### ISSUE THREAD

**Issue by dunn-cwu** [dunn-cwu/CS567_Project_2#1]
Standardization is preferred for data that does not have many outliers, otherwise use normalization. Do not standardize or normalize binary (1/0) columns.

**Comment by paulcollet** [comment]
Reminder: We discussed having the columns with a lot of zeros be normalized due to outliers, while the columns of non-zero results be standardized.

**Comment by safrannn** [comment]
https://medium.com/@swethalakshmanan14/how-when-and-why-should-you-normalize-standardize-rescale-your-data-3f083def38ff
since linear regression requires the data to have a gaussian distribution we need to do normalization on the data that doesn't have a normal distribution, which means all of the column except binary ones(normalization checked using plot). Below is the code for normalization.
normalize <- function(x) {
  return ((x - min(x)) / (max(x) - min(x)))
}
sdata$Size..acres. = normalize(data1$Size..acres.) # for a single column

And because different categories have different scale, we probably have to standardize the value across the columns. Below is the code, same as the code now.
sdata = as.data.frame(scale(data))

----
if someone is working on normalization or standardization please keep on working

**Comment by paulcollet** [comment]
Possibility?

# Normalize (from BBmisc module) all columns 
sdata <- as.data.frame(normalize(data))
names(sdata) <- colnames(data)

However, I get these warnings after step function:
Warning messages:
1: attempting model selection on an essentially perfect fit is nonsense 
2: attempting model selection on an essentially perfect fit is nonsense 
3: attempting model selection on an essentially perfect fit is nonsense 
4: attempting model selection on an essentially perfect fit is nonsense

**Comment by reevesba** [comment]
The model seems to perform better leaving 1/0 columns as is. As far as I understand, normalization suppresses the effect of outliers, so use that when we have outliers. Standardization assumes a Gaussian distribution like Su mentioned. I think the next step will be to plot the distribution of each feature and go from there. 

Just from testing, normalizing everything seemed to work better than standardizing everything.
